version: '3.3'
services:
  spark-master:
    image: rxvc/spark:2.4.0-master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
      - 6066:6066
      - 4040:4040
  spark-worker1:
    image: rxvc/spark:2.4.0-worker
    container_name: spark-worker1
    depends_on:
      - spark-master
    ports:
      - 8081:8081
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==node1"
  spark-worker2:
    image: rxvc/spark:2.4.0-worker
    container_name: spark-worker2
    depends_on:
      - spark-master
    ports:
      - 8082:8081
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "constraint:node==node2"
